# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6caa199f66ad8b5aa36f2dceb25488690dfa52dc808b6094a6834685a054d5cd7686c493f433c66b1c38b2e160924e255bbad7d765156836f421360edeaca76f

test:
  secret_key_base: 2a1286fbdc0c7251fc20786903e1f93df25a1ed828e48ae7ad099fbea49878781925c6ebd6b099fb166a80d1eb1614d988ba5c5de40655e16397575727f137f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
